version: "3.9"
services:
  app:
    image: altay
    container_name: altay
    command: sh -c "gunicorn --bind 0.0.0.0:8000 altay_backend.wsgi"

    volumes:
      - static_data:/altay/static
      - media:/altay/media
    restart: always
    ports:
      - "5900:8000"
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - static_data:/altay/static

volumes:
  media:
  static_data: