version: "3.9"
services:
  app:
    image: altay
    container_name: altay
    command: sh -c "gunicorn --bind 0.0.0.0:8000 altay_backend.wsgi"
    restart: always
    ports:
      - "5900:8000"
#  nginx:
#    container_name: altay_nginx
#    restart: on-failure
#    image: nginx:1.19.8
#    volumes:
#      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
#      - static_volume:static
#    depends_on:
#      - app
#    ports:
#      - "1337:80"
