version: "3.9"
services:
  app:
    image: altay
    container_name: altay
    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - media:/code/media
      - static:/code/static
    restart: always
    ports:
      - "5900:8000"

volumes:
  media:
  static: