version: "3.9"
services:
  app:
    image: altay
    container_name: altay
    volumes:
      - media:/code/media
      - static:/code/static
    restart: always
    ports:
      - "5900:8000"

volumes:
  media:
  static: